name: deploy-cloud-functions Integration

on:
  push:
    paths:
    - 'deploy-cloud-functions/**'
    - '.github/workflows/deploy-cf**'
  pull_request:
    paths:
    - 'deploy-cloud-functions/**'
    - '.github/workflows/deploy-cf**'

jobs:
  gcloud:
    name: with setup-gcloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master # Set up ADC for credentials
      with:
        service_account_email: ${{ secrets.DEPLOY_CF_SA_EMAIL }}
        service_account_key: ${{ secrets.DEPLOY_CF_SA_KEY_JSON }}
        export_default_credentials: true
    - id: deploy
      uses: ./deploy-cloud-functions
      env:
        GCLOUD_PROJECT: ${{ secrets.DEPLOY_CF_PROJECT_ID }}
      with:
        name: cf-http-gcloud-${{ github.run_number }}
        runtime: nodejs10
        entry_point: helloWorld
        source_dir: ./deploy-cloud-functions/tests/test-node-func/
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - run: npm install
      working-directory: ./deploy-cloud-functions
    - name: integration tests
      run: npm run e2e-tests
      working-directory: ./deploy-cloud-functions
      env:
        URL: ${{ steps.deploy.outputs.url }}
    - name: integration test clean up
      run: npm run cleanup
      working-directory: ./deploy-cloud-functions
      env:
        GCLOUD_PROJECT: ${{ secrets.DEPLOY_CF_PROJECT_ID }}
        DEPLOY_CF_SA_KEY_JSON: ${{ secrets.DEPLOY_CF_SA_KEY_JSON }}
        CF_NAME: ${{ steps.deploy.outputs.name }}

  b64_json:
    name: with base64 json creds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: deploy
      uses: ./deploy-cloud-functions
      with:
        name: cf-http-b64-${{ github.run_number }}
        runtime: nodejs10
        entry_point: helloWorld
        source_dir: ./deploy-cloud-functions/tests/test-node-func/
        credentials: ${{ secrets.DEPLOY_CF_SA_KEY_B64 }}
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - run: npm install
      working-directory: ./deploy-cloud-functions
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master # Set up ADC to make authenticated request to service
      with:
        service_account_email: ${{ secrets.DEPLOY_CF_SA_EMAIL }}
        service_account_key: ${{ secrets.DEPLOY_CF_SA_KEY_JSON }}
        export_default_credentials: true
    - name: integration tests
      run: npm run e2e-tests
      working-directory: ./deploy-cloud-functions
      env:
        URL: ${{ steps.deploy.outputs.url }}
    - name: integration test clean up
      run: npm run cleanup
      working-directory: ./deploy-cloud-functions
      env:
        GCLOUD_PROJECT: ${{ secrets.DEPLOY_CF_PROJECT_ID }}
        DEPLOY_CF_SA_KEY_JSON: ${{ secrets.DEPLOY_CF_SA_KEY_JSON }}
        CF_NAME: ${{ steps.deploy.outputs.name }}

  json:
    name: with json creds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: deploy
      uses: ./deploy-cloud-functions
      with:
        name: cf-http-json-${{ github.run_number }}
        runtime: nodejs10
        entry_point: helloWorld
        source_dir: ./deploy-cloud-functions/tests/test-node-func/
        credentials: ${{ secrets.DEPLOY_CF_SA_KEY_JSON }}
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - run: npm install
      working-directory: ./deploy-cloud-functions
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master # Set up ADC to make authenticated request to service
      with:
        service_account_email: ${{ secrets.DEPLOY_CF_SA_EMAIL }}
        service_account_key: ${{ secrets.DEPLOY_CF_SA_KEY_JSON }}
        export_default_credentials: true
    - name: integration tests
      run: npm run e2e-tests
      working-directory: ./deploy-cloud-functions
      env:
        URL: ${{ steps.deploy.outputs.url }}
    - name: integration test clean up
      run: npm run cleanup
      working-directory: ./deploy-cloud-functions
      env:
        GCLOUD_PROJECT: ${{ secrets.DEPLOY_CF_PROJECT_ID }}
        DEPLOY_CF_SA_KEY_JSON: ${{ secrets.DEPLOY_CF_SA_KEY_JSON }}
        CF_NAME: ${{ steps.deploy.outputs.name }}

