name: deploy-cloudrun credentials Integration

on:
  push:
    paths:
    - 'deploy-cloudrun/**'
    - '.github/workflows/deploy-cloudrun-credentials-it.yml'
  pull_request:
    paths:
    - 'deploy-cloudrun/**'
    - '.github/workflows/deploy-cloudrun-credentials-it.yml'

jobs:
  gcloud:
    name: with setup-gcloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./setup-gcloud # Set up ADC to make authenticated request to service
      with:
        service_account_key: ${{ secrets.DEPLOY_CLOUDRUN_SA_KEY_B64 }}
        export_default_credentials: true
    - id: deploy
      uses: ./deploy-cloudrun
      with:
        image: gcr.io/cloudrun/hello
        service: test-gcloud
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - run: npm install
      working-directory: ./deploy-cloudrun
    - name: integration tests
      run: npm run e2e-tests
      working-directory: ./deploy-cloudrun
      env:
        URL: ${{ steps.deploy.outputs.url }}

  b64_json:
    name: with base64 json creds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: deploy
      uses: ./deploy-cloudrun
      with:
        credentials: ${{ secrets.DEPLOY_CLOUDRUN_SA_KEY_B64 }}
        image: gcr.io/cloudrun/hello
        service: test-b64
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - run: npm install
      working-directory: ./deploy-cloudrun
    - uses: ./setup-gcloud # Set up ADC to make authenticated request to service
      with:
        service_account_key: ${{ secrets.DEPLOY_CLOUDRUN_SA_KEY_B64 }}
        export_default_credentials: true
    - name: integration tests
      run: npm run e2e-tests
      working-directory: ./deploy-cloudrun
      env:
        URL: ${{ steps.deploy.outputs.url }}

  json:
    name: with json creds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: deploy
      uses: ./deploy-cloudrun
      with:
        credentials: ${{ secrets.DEPLOY_CLOUDRUN_SA_KEY_JSON }}
        image: gcr.io/cloudrun/hello
        service: test-json
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - run: npm install
      working-directory: ./deploy-cloudrun
    - uses: ./setup-gcloud # Set up ADC to make authenticated request to service
      with:
        service_account_key: ${{ secrets.DEPLOY_CLOUDRUN_SA_KEY_B64 }}
        export_default_credentials: true
    - name: integration tests
      run: npm run e2e-tests
      working-directory: ./deploy-cloudrun
      env:
        URL: ${{ steps.deploy.outputs.url }}
